databases:
  mysql:
    username: "root"
    password: "root"
    port: "localhost:8889"
    dbname: "test"
    
  redis:
    port: "localhost:6379"

  elastic:
    port: "http://192.168.0.65:9200/"

  server:
    port: "localhost:8000"


   